### ISSUE TITLE
Issues with MobileDatePicker (Material UI): Uncaught TypeError: _this.child(...).get is not a function

### ISSUE THREAD

**Issue by malte94** [avkonst/hookstate#285]
So I am using the following approach to set a date in Material UI's MobileDatePicker:

```
<LocalizationProvider locale={de} dateAdapter={AdapterDateFns}>
  <MobileDatePicker defaultValue={null} label="Erstbesuch" inputFormat="dd.MM.yyyy"
    okText="Ok"
    clearText="Zurücksetzen"
    cancelText="Abbrechen"
    value={customer.get().cards?.types?.pod_compact?.ersttermin || new Date()}
    onChange={d => d && customer.cards.types.pod_compact.ersttermin.set(d)}
    renderInput={(params) => <MUI.TextField className="w-100" variant="outlined" {...params} />}
  />
</LocalizationProvider>
```

This leads to the following console error:

```
Uncaught TypeError: _this.child(...).get is not a function
    at Object.get (index.ts:1421:1)
    at Proxy.[Symbol.toPrimitive] (<anonymous>)
    at new Date (<anonymous>)
    at DateFnsUtils.date (index.esm.js:231:1)
    at validateDate (date-utils.js:91:1)
    at useValidation (useValidation.js:22:1)
    at useDateValidation (useValidation.js:37:1)
    at MobileDatePicker (MobileDatePicker.js:34:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at updateForwardRef (react-dom.development.js:19968:1)
```

Using the same approach with other fields, or useState, works without any issues on the other hand:

```
<MobileDatePicker defaultValue={null} label="Rechnungsdatum" inputFormat="dd.MM.yyyy"
    okText="Ok"
    clearText="Zurücksetzen"
    cancelText="Abbrechen"
    value={invoiceDate ? invoiceDate : new Date()}
    onChange={d => d && setInvoiceDate(d)}
    renderInput={(params) => <MUI.TextField fullWidth variant="outlined" {...params} />}
/>
</LocalizationProvider>
```

**Comment by avkonst** [comment]
Hi, thank s for ticket. I could have a look at it, but I need a reproducer which I could run locally or online, please?

**Comment by malte94** [comment]
Thank you for your prompt reply! :)

Here: https://stackblitz.com/edit/react-pwrtls

**Comment by avkonst** [comment]
I have commented out all hookstate related code and the problem still present. You may need to contact MobileDatePicker

```
import React from 'react';
import MobileDatePicker from '@mui/lab/MobileDatePicker';
// import AdapterDateFns from '@mui/lab/AdapterDateFns';
// import LocalizationProvider from '@mui/lab/LocalizationProvider';
import * as MUI from '@mui/material';
// import { useHookstate } from '@hookstate/core';

export default function App() {
  // const customer = useHookstate([]);

  return (
    <div className="App">
      <MobileDatePicker
        defaultValue={null}
        label="Erstbesuch"
        inputFormat="dd.MM.yyyy"
        okText="Ok"
        clearText="Zurücksetzen"
        cancelText="Abbrechen"
        value={
          // customer.get().cards?.types?.pod_compact?.ersttermin || new Date()
        }
        onChange={(d) =>
          {}
          // d && customer.cards.types.pod_compact.ersttermin.set(d)
        }
        renderInput={(params) => (
          <MUI.TextField className="w-100" variant="outlined" {...params} />
        )}
      />
    </div>
  );
}

```

![image](https://user-images.githubusercontent.com/3971413/169431403-4782b5e2-78af-4259-9d7c-6c5e22e9a9f8.png)

**Comment by malte94** [comment]
Thank you @avkonst! I think Stackblitz is just not working properly there. If you have time, maybe you could try this with a local npx create app?

**Comment by malte94** [comment]
The following approach with useState() definitely works on my side:

```
                <LocalizationProvider locale={de} dateAdapter={AdapterDateFns}>
                  <MobileDatePicker defaultValue={null} label="Erstbesuch" inputFormat="dd.MM.yyyy"
                    okText="Ok"
                    clearText="Zurücksetzen"
                    cancelText="Abbrechen"
                    value={customer.cards?.types?.pod_compact?.ersttermin || new Date()}
                    onChange={d => d && setCustomer((c) => { c.cards.types.pod_compact.ersttermin = d; return { ...c } })}
                    renderInput={(params) => <MUI.TextField className="w-100" variant="outlined" {...params} />}
                  />
                </LocalizationProvider>
```

**Comment by avkonst** [comment]
You hit the limitation of dealing with complex types. It will get addressed here https://github.com/avkonst/hookstate/issues/106
