### ISSUE TITLE
Conflict with NavigationContainer from @react-navigation/native

### ISSUE THREAD

**Issue by adrianofoschi** [avkonst/hookstate#296]
Hey,
I am using HookState inside a react-native application. In the same application I am using NavigationContainer from the popular routing library "react-navigation".
The combination of the both libraries generates an error into the "useHookEffect" function.

Example code:
```
import { NavigationContainer } from '@react-navigation/native';
import { createState } from '@hookstate/core';

export default function App() {
  return (
      <NavigationContainer>
      </NavigationContainer>
  );
}
```

Error stack:
```
index.es.js:1284 Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(self)')
    at Object.useHookEffect [as useEffect] (index.es.js:1284:1)
    at useLinking (useLinking.tsx:314:1)
    at NavigationContainerInner (NavigationContainer.tsx:76:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateForwardRef (react-dom.development.js:17044:1)
    at beginWork (react-dom.development.js:19098:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21881:1)
    at updateContainer (react-dom.development.js:25482:1)
    at react-dom.development.js:26021:1
    at unbatchedUpdates (react-dom.development.js:22431:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020:1)
    at render (react-dom.development.js:26103:1)
    at renderApplication (renderApplication.js:23:1)
    at Object.run (index.js:49:1)
    at Function.runApplication (index.js:93:1)
    at registerRootComponent (registerRootComponent.tsx:14:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:5:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (AuthState.js:20:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
```

The error is at the line 1283 of the compiled "index.es.js" of HookState. 
```
function useHookEffect(effect, deps) {
    for (var _i = 0, _a = deps || []; _i < _a.length; _i++) {
        var i = _a[_i];
        var state = i[self];
        if (state) {
            state.reconnect();
        }
    }
    return originUseEffect(effect, deps);
}
```

We have `_a = [0: false, 1: undefined]`
undefined `_a[1]` seems the problem.

Image from debugger:
![Screenshot_20220609_201000](https://user-images.githubusercontent.com/4822527/172916735-5cbc37e1-98c3-4aad-8b5a-92f5ac82618f.png)

I am newbie at react-native and your library. So I have not idea where "undefined" come from.
Actually I simply solved adding a check on `i` as follow:

```
function useHookEffect(effect, deps) {
    for (var _i = 0, _a = deps || []; _i < _a.length; _i++) {
        var i = _a[_i];
        if (i) {
            var state = i[self];
            if (state) {
                state.reconnect();
            }
        }
    }
    return originUseEffect(effect, deps);
}
```

I hope it will be useful for a correction

**Comment by avkonst** [comment]
Hi, thanks for reporting. You are on the version 4-rc2 or rc3.. Hookstate for has not been stabilized yet. The bug is known and the pull request fixing it was merged a week or two ago. I have released 4.0.0-rc4 version for you which contains the fix.
